[build]
  functions = "functions" # Directory where serverless functions are stored
  publish = "public"            # Directory with static files to publish

[[redirects]]
  from = "/auth-config"
  to = "/.netlify/functions/auth-config"
  status = 200
